---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-identity-company-org-v3-useridentityv3
  failurePolicy: Fail
  name: museridentityv3.kb.io
  rules:
  - apiGroups:
    - identity.company.org
    apiVersions:
    - v3
    operations:
    - CREATE
    - UPDATE
    resources:
    - useridentityv3s
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-identity-company-org-v3-useridentityv3
  failurePolicy: Fail
  name: vuseridentityv3.kb.io
  rules:
  - apiGroups:
    - identity.company.org
    apiVersions:
    - v3
    operations:
    - CREATE
    - UPDATE
    resources:
    - useridentityv3s
  sideEffects: None
